spring.application.name=ztpai-projekt

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret=my-super-secret-key-for-jwt-token-123456789
security.jwt.expiration-ms=3600000